apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/argocd
- ingress.yaml

patches:
- path: argocd-rbac-cm.yaml
- path: argocd-cm.yaml
- path: argocd-image-updater-config.yaml
