apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/huuduc8404/k8s-assessment-monorepo.git
    path: k8s/dev/argocd
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
    - ServerSideApply=true
    - RespectIgnoreDifferences=true
    - CreateNamespace=true
