apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- argocd.yaml
- backend.yaml
- docker-registry.yaml
- frontend.yaml
- image-updater.yaml
- jenkins.yaml
- nfs-provisioner.yaml
- nfs-server.yaml